from PyLinq.interpreter import run


def main(sql_expr: str, data_sources: dict):
    print(run(sql_expr, data_sources))


if __name__ == '__main__':
    s = """(SELECT ID, SUM(PRICE) AS II FROM TABLE CROSS JOIN TABLE2 WHERE TABLE.ID=TABLE2.TABLE_ID
AND TABLE.NAME=TABLE.HELLO AND TABLE.AGE IN (SELECT TABLE1.AGE2 FROM TABLE1) ORDER BY DATE LIMIT 10)

(SELECT * FROM MOBILE WHERE MOBILE.COMPANY_ID = 1 OR MOBILE.ID = 1)

(SELECT * FROM MOBILE WHERE MOBILE.COMPANY_ID = 1 + MOBILE.ID > 5)

(SELECT * FROM MOBILE WHERE MOBILE.COMPANY_ID - MOBILE.ID < 3
AND MOBILE.COMPANY_ID - MOBILE.ID > 0)

(SELECT COMPANY.NAME AS COMPANY_NAME, MOBILE.NAME AS MOBILE_NAME
FROM MOBILE, COMPANY WHERE MOBILE.COMPANY_ID = COMPANY.ID
AND MOBILE.NAME = 'XIAOMI3')

(SELECT MOBILE.NAME AS MOBILE_NAME, COMPANY.NAME AS COMPANY_NAME, CEO.NAME AS CEO_NAME
FROM MOBILE, COMPANY, CEO WHERE MOBILE.COMPANY_ID = COMPANY.ID
AND COMPANY.ID = CEO.COMPANY_ID AND CEO.NAME = 'RENZHENGFEI')

(SELECT SUM(MOBILE.ID) AS SUM_MOBILE_ID, SUM(MOBILE.COMPANY_ID) AS SUM_COMPANY_ID FROM MOBILE)

(SELECT COUNT(*) AS COUNT1 FROM MOBILE)

(SELECT MOBILE.COMPANY_ID, COUNT(*) AS COUNT1 FROM MOBILE GROUP BY MOBILE.COMPANY_ID)

(SELECT MOBILE.COMPANY_ID, COUNT(*) AS COUNT1 FROM MOBILE GROUP BY MOBILE.COMPANY_ID HAVING
COUNT(*) >= 2 AND MOBILE.COMPANY_ID != 4)

(SELECT MOBILE.NAME AS MOBILE_NAME, COMPANY.NAME AS COMPANY_NAME, CEO.NAME AS CEO_NAME
FROM MOBILE, COMPANY, CEO WHERE MOBILE.COMPANY_ID = COMPANY.ID AND COMPANY.ID = CEO.COMPANY_ID
AND MOBILE.NAME = 'MATE20')

(SELECT MOBILE.NAME AS MOBILE_NAME, COMPANY.NAME AS COMPANY_NAME, CEO.NAME AS CEO_NAME FROM MOBILE, COMPANY,
CEO WHERE MOBILE.COMPANY_ID = COMPANY.ID AND COMPANY.ID = CEO.COMPANY_ID AND MOBILE.NAME = 'MATE20')

(SELECT MOBILE.NAME AS MOBILE_NAME, COMPANY.NAME AS COMPANY_NAME, CEO.NAME AS CEO_NAME FROM MOBILE, COMPANY, CEO
WHERE MOBILE.COMPANY_ID = COMPANY.ID AND COMPANY.ID = CEO.COMPANY_ID AND '1' = 'MATE20')

(SELECT SUM(MOBILE.ID) AS SUM1 FROM MOBILE)

(SELECT MOBILE.COMPANY_ID FROM MOBILE ORDER BY MOBILE.COMPANY_ID ASC)

(SELECT MOBILE.COMPANY_ID FROM MOBILE ORDER BY MOBILE.COMPANY_ID DESC)

(SELECT MOBILE.COMPANY_ID FROM MOBILE GROUP BY MOBILE.COMPANY_ID ORDER BY MOBILE.COMPANY_ID)

(SELECT MOBILE.COMPANY_ID, MOBILE.NAME FROM MOBILE WHERE MOBILE.NAME IN ('XIAOMI2', 'XIAOMI3', 'MATE20'))

(SELECT MOBILE.COMPANY_ID, MOBILE.NAME FROM MOBILE WHERE MOBILE.NAME NOT IN ('XIAOMI2', 'XIAOMI3', 'MATE20'))

(SELECT MOBILE.COMPANY_ID, MOBILE.NAME FROM MOBILE WHERE MOBILE.COMPANY_ID IN (SELECT COMPANY.ID FROM COMPANY))

(SELECT CASE WHEN COMPANY.NAME = 'XIAOMI' THEN '小米' WHEN COMPANY.NAME ='HUAWEI' THEN '华为'
WHEN COMPANY.NAME ='APPLE' THEN '苹果' ELSE '' END AS COMPANY_NAME FROM COMPANY)

(SELECT RENAME('*', 'NAME:公司,ID:ID') FROM COMPANY)

(SELECT RENAME('*', 'NAME:公司,ID:ID') FROM COMPANY)

(SELECT SUM(INT(MOBILE.ID)) AS SUM1, MOBILE.COMPANY_ID FROM MOBILE GROUP BY MOBILE.COMPANY_ID)

(SELECT DEFLATE(CEO.NAME, 'CEO_NAME', MOBILE_PRICE.TYPE, SUM(MOBILE_PRICE.PRICE), '0:普通,1:旗舰', 0)
FROM MOBILE, COMPANY, CEO, MOBILE_PRICE WHERE MOBILE.ID = MOBILE_PRICE.MOBILE_ID
AND MOBILE.COMPANY_ID = COMPANY.ID AND COMPANY.ID = CEO.COMPANY_ID GROUP BY CEO.NAME, MOBILE_PRICE.TYPE)
"""
    test_sql_expr = "(SELECT Teacher.name FROM Teacher WHERE Teacher.year = 5)"
    test_data = {
        'Teacher': [
            {'name': 'zhang', 'year': 5},
            {'name': 'li', 'year': 3}
        ],
        'Student': [
            {'number': 10, 'age': 18},
            {'number': 20, 'age': 17}
        ]
    }
    main(test_sql_expr, test_data)
